### ISSUE TITLE
Rebooting when motor running

### ISSUE THREAD

**Issue by ishioni** [kireque/esphome_nebula_light#2]
I seem to have a problem that when i run the motor, the device will reboot after some random amount of time. Any idea why that might be? My PCB looks a tad different then yours - the module was on the same side as the connectors, but apart from that seems to work identical. Also I used a 1K resistor between GPIO15 and ground - without it i had 12K resistance to GND and 10K resistance to VCC, but have no idea if that makes any difference

**Comment by kireque** [comment]
I have never seen the issue you describe, so cannot say I recognize this behavior. 

Also not sure If I can help you with this as I am not a electrician. I did manage this to work by using reverse engineering, but not sure how to troubleshoot your issue unfortunately... Maybe someone sees your issue here and will reply with a possible solution. Wil leave the issue open for now.

**Comment by Th3M1k3y** [comment]
Is your power supply strong enough? I tried with a random 0.6A rated, and when getting close to stall speed on the motor, the microcontroller would just reset. After changing to an old 1A from an old iphone the problem went away.

**Comment by nechry** [comment]
I also have a different pcb. for now I have 2 issues:
motor won't work
a soon a press the button the esp become unreachable, need a hard reboot.
I use during the test a lab power-supply with 2 amp.

I got difficulty to remove the wifi chip, because it's was also glued.

@ishioni do you progress from your side?

**Comment by nechry** [comment]
ok good new from my side: the motor now work, it's was a bad connection from gpio13 to the motor control input. 
Also I fine tune the pwm for best usage of the slider by adjusting the min/max percentage

```yaml
  - platform: esp8266_pwm
    id: motor_pwm
    pin: GPIO13
    min_power: 13%
    max_power: 80%
    frequency: 1000 Hz
```

a min_power at 29% for the laser also give us more range.

```yaml
- platform: esp8266_pwm
    id: laser_pwm
    pin: GPIO5
    min_power: 29%
    inverted: true
```

I didn't yet find the problem with input button, connection are ok, level is correctly shifted, event occurred but immediately loose the remote access to the device.
