### ISSUE TITLE
Motor speed

### ISSUE THREAD

**Issue by Th3M1k3y** [kireque/esphome_nebula_light#3]
I just did this to my nebula light too, and it is working great.

One thing I noticed was the motor speed had a pretty limited range where the speed was actually adjusted. Changing that from being a light to being a fan disable light correction, and instead return a linear output. This makes it easier to adjust the speed of the motor.

**Comment by kireque** [comment]
Can you share your code? 
I will update the readme.

Or create a pull request. :)

**Comment by Th3M1k3y** [comment]
I have changed too much to just be able to make a pull request, but I can share the fan part

```yaml
fan:
  platform: speed
  name: "${friendly_name} Motor"
  id: motor
  output: motor_pwm
  restore_mode: ALWAYS_OFF
```

and then just remove the

```yaml
  - platform: monochromatic
    name: "${friendly_name} Motor"
    id: motor
    output: motor_pwm
    restore_mode: ALWAYS_OFF
```
part under light.

To set the speed with the button press you need to change it to

```yaml
        - output.set_level:
            id: motor_pwm
            level: 25%
```
